apiVersion: core.k8s.appscode.com/v1alpha1
kind: ResourceCalculator
request:
  apiVersion: kubedb.com/v1alpha2
  kind: MongoDB
  metadata:
    labels:
      app.kubernetes.io/instance: fasd
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: mongodbs.kubedb.com
    name: fasd
    namespace: default
  spec:
    clusterAuthMode: keyFile
    monitor:
      agent: prometheus.io/operator
      prometheus:
        exporter:
          args:
          - "--compatible-mode"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        serviceMonitor:
          interval: 30s
          labels:
            release: kube-prometheus-stack
    podTemplate:
      spec:
        resources:
          limits:
            cpu: ".5"
            memory: 1024Mi
    replicas: 1
    sslMode: disabled
    storage:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: linode-block-storage-retain
    storageType: Durable
    terminationPolicy: WipeOut
    version: 4.1.7-v3
