apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/component: panopticon
    app.kubernetes.io/part-of: opscenter-monitoring
  name: panopticon
  namespace: kubeops
spec:
  chart:
    spec:
      chart: panopticon
      sourceRef:
        kind: HelmRepository
        name: kubeops
        namespace: kubeops
      version: v2023.03.23
  install:
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: -1
  interval: 5m
  releaseName: panopticon
  storageNamespace: monitoring
  targetNamespace: monitoring
  timeout: 30m
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
