apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app.kubernetes.io/instance: panopticon
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: panopticon
    app.kubernetes.io/version: v0.0.9
    helm.sh/chart: panopticon-v2023.03.23
    helm.toolkit.fluxcd.io/name: panopticon
    helm.toolkit.fluxcd.io/namespace: kubeops
  name: panopticon
  namespace: cattle-project-p-tkgpc-monitoring
subsets:
- addresses:
  - ip: 10.128.222.88
  ports:
  - name: api
    port: 443
    protocol: TCP
  - name: telemetry
    port: 8081
    protocol: TCP
