apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: quick-postgres
  namespace: app-3-ns1
spec:
  version: "13.2"
  storageType: Durable
  storage:
    storageClassName: "linode-block-storage"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: Delete