apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-grantor
  namespace: kubeops
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
  resourceNames: ["kube-ui-server"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["kube-ui-server-apiserver-cert"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-grantor-binding
  namespace: kubeops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-grantor
subjects:
- kind: ServiceAccount
  name: rancher-monitoring-operator
  namespace: cattle-monitoring-system

# subjects:
# - kind: Group
#   name: system:serviceaccounts:cattle-project-p-tkgpc-monitoring
#   apiGroup: rbac.authorization.k8s.io
# - kind: Group
#   name: system:serviceaccounts:cattle-project-p-mrbgq-monitoring
#   apiGroup: rbac.authorization.k8s.io
# - kind: Group
#   name: system:serviceaccounts:cattle-project-p-p5zwg-monitoring
#   apiGroup: rbac.authorization.k8s.io
