apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: panopticon-prom-role-grantor
  namespace: monitoring
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: panopticon-prom-role-grantor-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: panopticon-prom-role-grantor
subjects:
- kind: ServiceAccount
  name: cattle-project-p-tkgpc-mon-prometheus
  namespace: cattle-project-p-tkgpc-monitoring
- kind: Group
  name: system:serviceaccounts:cattle-project-p-tkgpc-monitoring
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:serviceaccounts:cattle-project-p-mrbgq-monitoring
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:serviceaccounts:cattle-project-p-p5zwg-monitoring
  apiGroup: rbac.authorization.k8s.io
